# Generated by Django 6.1.1 on 2026-10-05 19:29
from django.db import migrations


def normalize_user_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    db_alias = schema_editor.connection.alias
    users = list(User.objects.using(db_alias).all())
    emails = {}
    for user in users:
        email = (user.email or "").strip().lower()
        if not email:
            raise ValueError(f"Пустой email у пользователя id={user.pk}")

        if email in emails:
            raise ValueError(f"Конфликт email у пользователя id={user.pk} и id={emails[email]}")

        user.email = email
        emails[email] = user.pk

    for user in users:
        user.save(using=db_alias, update_fields=["email"])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            normalize_user_emails,
            migrations.RunPython.noop,
        ),
    ]
